### ISSUE TITLE
Feature Request: Validate Domain Spellings

### ISSUE THREAD

**Issue by arunpugahz** [romainsimon/emailvalid#2]
This is really a great package. Thanks, Appreciate it.
It would be great if this could support spell check for most common domains.
[ gnail.com -> gmail.com ]
[ gmail.con -> gmail.com ]
These are the common typos that happen while filling up the form.

**Comment by romainsimon** [comment]
Thanks for the suggestion @arunpugahz !
This has been added in the 1.0.4 version of `emailvalid`
